# â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
# â”‚ ğŸ™ GITHUB ACIONS CI/CD WORKFLOW                                  â”‚
# â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯

name: 'â™»ï¸ sync labels'

on:
  push:
    branches:
      - chore/miscellenous/draft/3
#

jobs:

  auto-repository-label-sync:
    name: â™»ï¸ JOB - Sync labels
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: srealmoreno/label-sync-action@v2
        # with:
        # â•­â”€â”€â”€â”€â”€
        # â”‚ NOTE: WARNING:
        # â”‚ |: This will delete any labels not defined in the config file.
        # â•°â”€â”€â”€â”€â”€
        #   clean-labels: true
  #
#